import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const srcPath = join(root, '..', 'js', 'db.js')
const outDir = join(root, 'supabase')

const raw = readFileSync(srcPath, 'utf8')
const body = raw.replace(/^const\s+DB\s*=\s*/, '').replace(/;\s*$/, '')
const DB = new Function(`return (${body});`)()
if (!DB || !Array.isArray(DB.slides)) throw new Error('db.js did not evaluate to a DB object')

let events = []

DB.slides.forEach((it, i) => events.push({ category: 'hero', sort: i, ...it }))
DB.newEvents.forEach((it, i) => events.push({ category: 'new', sort: i, ...it }))
DB.popularEvents.forEach((it, i) => events.push({ category: 'popular', sort: i, ...it }))
events.push({ category: 'recommend', sort: 0, ...DB.recommend })
DB.others.forEach((it, i) =>
  events.push({ category: 'others', sort: i, ...it, title: it.name })
)
DB.registerEvents.forEach((it, i) =>
  events.push({ category: 'register', sort: i, ...it, title: it.name })
)

const current = {
  category: 'current',
  sort: 0,
  ...DB.currentEvent,
  title: DB.currentEvent.name || DB.currentEvent.title,
  extra: {
    tag: DB.currentEvent.tag,
    desc: DB.currentEvent.desc,
    highlights: DB.currentEvent.highlights,
    distances: DB.currentEvent.distances,
    earlyBird: DB.currentEvent.earlyBird,
    pack: DB.currentEvent.pack,
    schedule: DB.currentEvent.schedule,
    rules: DB.currentEvent.rules,
    contact: DB.currentEvent.contact,
    limit: DB.currentEvent.limit,
  },
}
delete current.name
events.push(current)

// Dev convenience: SEED_ONLY="id1,id2" slims the seed down to a few events
// (e.g. the registerable current event + one hero slide) so the local build
// stays small. The current event is always kept available as the single
// "เปิดรับสมัคร" register card so the homepage section is never empty.
const only = (process.env.SEED_ONLY || '')
  .split(',')
  .map((s) => s.trim())
  .filter(Boolean)

if (only.length) {
  events = events.filter((e) => only.includes(e.id))
  if (events.length === 0) throw new Error('SEED_ONLY matched no events')
  const cur = events.find((e) => e.category === 'current') ?? current
  if (!events.some((e) => e.category === 'register')) {
    // Promote the current event's own row to the register card instead of
    // pushing a duplicate: the rows share one id, so the second INSERT
    // would collide on the primary key and the register card would vanish.
    const row = events.find((e) => e.id === cur.id)
    if (row && row.category === 'current') row.category = 'register'
    else events.push({ ...cur, category: 'register', sort: 0 })
  }
}

const seed = {
  meta: { year: DB.year },
  nav: DB.nav,
  footer: DB.footer,
  current,
  organizer: DB.organizer,
  events,
}

mkdirSync(outDir, { recursive: true })
const jsonPath = join(outDir, 'seed.json')
const sqlPath = join(outDir, 'seed.sql')
writeFileSync(jsonPath, JSON.stringify(seed, null, 2) + '\n', 'utf8')

const esc = (v) =>
  v === null || v === undefined
    ? 'NULL'
    : `'${String(v).replace(/'/g, "''")}'`
const json = (v) =>
  v === undefined || v === null ? 'NULL' : `'${JSON.stringify(v).replace(/'/g, "''")}'`
const num = (v) => (v === undefined || v === null ? 'NULL' : String(v))

const rows = events.map((e) => {
  const {
    id, code, category, sort, tag, tagType, title, sub, date, start, place,
    org, dist, distLabel, deadline, slotsLeft, slotsTotal, grad, route, ghost, extra,
  } = e
  return `('${id}', ${esc(code)}, ${esc(category)}, ${num(sort)}, ${esc(tag)}, ${esc(tagType)}, ${esc(title)}, ${esc(sub)}, ${esc(date)}, ${esc(start)}, ${esc(place)}, ${esc(org)}, ${esc(dist)}, ${esc(distLabel)}, ${esc(deadline)}, ${num(slotsLeft)}, ${num(slotsTotal)}, ${esc(grad)}, ${esc(route)}, ${esc(ghost)}, ${json(extra)})`
})

const clearEvents = only.length
  ? `DELETE FROM public.events;\n\n`
  : ''

const sql = `-- Auto-generated by scripts/build-seed.mjs from js/db.js — do not edit by hand.
-- Run in the Supabase SQL editor (or psql). Re-run is idempotent (DO NOTHING).
-- SEED_ONLY mode replaces the events table so the DB mirrors the seed.

${clearEvents}INSERT INTO public.events
  (id, code, category, sort, tag, tag_type, title, sub, date, start, place, org, dist, dist_label, deadline, slots_left, slots_total, grad, route_color, ghost_color, extra)
VALUES
${rows.join(',\n')}
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.organizer_content
  (id, support_email, hero_slides, roadmap, stats_track, stats_community, trusted, services, form)
VALUES
  ('default', ${esc(DB.organizer.supportEmail)}, ${json(DB.organizer.heroSlides)}, ${json(DB.organizer.roadmap)}, ${json(DB.organizer.statsTrack)}, ${json(DB.organizer.statsCommunity)}, ${json(DB.organizer.trusted)}, ${json(DB.organizer.services)}, ${json(DB.organizer.form)})
ON CONFLICT (id) DO NOTHING;
`

writeFileSync(sqlPath, sql, 'utf8')

const kb = (p) => (Buffer.byteLength(readFileSync(p, 'utf8'), 'utf8') / 1024).toFixed(1)
console.log(`seed.json (${kb(jsonPath)} KB) and seed.sql (${kb(sqlPath)} KB) written to ${outDir}`)
console.log(`events: ${events.length}  categories: ${[...new Set(events.map((e) => e.category))].join(', ')}`)
console.log(`unique event ids: ${[...new Set(events.map((e) => e.id))].length}${only.length ? `  (SEED_ONLY=${only.join(',')})` : ''}`)
console.log('meta.year:', DB.year, ' nav:', DB.nav.length, ' organizer.form.topics:', DB.organizer.form.topics.length)